---
snakefile: snakefile
latency-wait: 60
reason: True
show-failed-logs: True
# keep-going: True
printshellcmds: True
# rerun-incomplete: True
# restart-times: 3
# Cluster submission
jobname: "{rule}.{jobid}"              # Provide a custom name for the jobscript that is submitted to the cluster.
max-jobs-per-second: 100                #Maximal number of cluster/drmaa jobs per second, default is 10, fractions allowed.
max-status-checks-per-second: 10       #Maximal number of job status checks per second, default is 10
jobs: 500                               #Use at most N CPU cluster/cloud jobs in parallel.
cluster: "sbatch --output=HOMEDIR/slurm_logs/%j.out --error=HOMEDIR/slurm_logs/%j.err --nodes={resources.nodes} --partition={resources.slurm_partition} --mem={resources.mem_mb} --time={resources.runtime} --cpus-per-task={resources.cpus_per_task}"
# Job resources
default-resources:
  - slurm_partition=main
  - mem_mb=4000
  - runtime="3-00:00:00"
  - nodes=1
  - cpus_per_task=1
